/** Static legal context for evidence-style exports (not legal advice). */
export const REPORT_LEGAL_CONTEXT =
  "Relevant Pakistan frameworks often cited in such matters include: Protection Against Harassment of Women at the Workplace Act 2010; Prevention of Electronic Crimes Act (PECA) 2016 for online abuse; PPC §354 (assault on modesty) and §509 (word/gesture insulting modesty). Consult a qualified lawyer for your specific case.";

export function buildIncidentReportText({ report, aiInsight, submittedAt, gpsLabel }) {
  const id = report?.id || "unknown";
  const city = report?.city || "";
  const category = report?.category || "";
  const area = report?.area || "";
  const description = report?.description || "";
  const level = report?.level || "";
  const status = report?.status || "";
  const time = submittedAt || report?.time || new Date().toISOString();
  const ai = (aiInsight || report?.aiSummary || "").trim();
  const gps = gpsLabel || (typeof report?.lat === "number" && typeof report?.lon === "number" ? `${report.lat}, ${report.lon}` : "Not attached");

  return [
    "══════════════════════════════════════════════════════════════",
    "  NIgaban (نگہبان) — SAFETY INCIDENT REPORT (self-generated)",
    "══════════════════════════════════════════════════════════════",
    "",
    `Report ID: ${id}`,
    `Recorded (UTC): ${time}`,
    `City: ${city}`,
    `Category: ${category}`,
    `Area / landmark: ${area}`,
    `Severity flag: ${level}`,
    `Moderation status: ${status}`,
    "",
    "— DESCRIPTION —",
    description,
    "",
    "— LOCATION —",
    gps,
    "",
    "— AI SAFETY SUMMARY (informational; not a legal opinion) —",
    ai || "(No AI summary was returned for this record.)",
    "",
    "— LEGAL ORIENTATION (general information only) —",
    REPORT_LEGAL_CONTEXT,
    "",
    "— DISCLAIMER —",
    "This file was generated by the NIgaban app for your records. It is not a police FIR, court filing, or legal advice.",
    "If you are in immediate danger, call 15 (police) or 1099 (women’s helpline).",
    "",
    "End of report",
    "",
  ].join("\n");
}

export function downloadIncidentReport(text, filenameBase = "nigaban-safety-report") {
  const safe = String(filenameBase).replace(/[^\w.-]+/g, "-").slice(0, 48);
  const blob = new Blob([text], { type: "text/plain;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${safe}.txt`;
  a.rel = "noopener";
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}

export function printIncidentReportAsPdf(text) {
  const w = window.open("", "_blank", "noopener,noreferrer,width=720,height=900");
  if (!w) return;
  const escaped = String(text)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
  w.document.write(`<!DOCTYPE html><html><head><meta charset="utf-8"/><title>NIgaban safety report</title>
  <style>
    @media print { @page { margin: 16mm; } }
    body { font-family: ui-sans-serif, system-ui, sans-serif; font-size: 11px; line-height: 1.45; color: #111; max-width: 640px; margin: 24px auto; padding: 0 12px; white-space: pre-wrap; }
    h1 { font-size: 14px; margin: 0 0 12px; }
  </style></head><body>
  <h1>NIgaban — Safety incident report</h1>
  <pre style="white-space:pre-wrap;font:inherit;margin:0">${escaped}</pre>
  <script>window.onload=function(){window.print();}</script>
  </body></html>`);
  w.document.close();
}
